### ISSUE TITLE
1.8.9 - Crash when breaking coloured chest bed in creative mode

### ISSUE THREAD

**Issue by katubug** [ZornTaov/BedcraftAndBeyond#10]
Item was the Red Blanket/White Sheet/Xylex Plank Frame, and I attempted to break it by left clicking on the "bottom" tile (foot of the bed).

Crash Report: [crash-2016-08-11_21.57.23-client.txt](https://github.com/ZornTaov/BedcraftAndBeyond/files/414572/crash-2016-08-11_21.57.23-client.txt)

I apologize if this version is no longer being supported, just thought I'd help.

**Comment by ZornTaov** [comment]
try using version 2.0.3 for 1.8.9

**Comment by ZornTaov** [comment]
Closing as this should be fixed with no response
