### ISSUE TITLE
Conflict with tinkers mod

### ISSUE THREAD

**Issue by aquagirl555** [ZornTaov/BedcraftAndBeyond#11]
I was told to inform you that when both bedcraftandbeyong and the tinkers mods are both used,  and  trying to use the stencil table, minecraft crashes, I went over there and apparently this mod is to blame _shrugs_ here's the link to the other thread i made.

https://github.com/SlimeKnights/TinkersConstruct/issues/2353#issuecomment-243842831
 i really want to use bedcraft and beyond, but mainly for the cosmetics, so tinkers takes priority, but I would still like to use both.

**Comment by ZornTaov** [comment]
Already fixed with BCB 2.4.1 for minecraft 1.10.2, please update
