### ISSUE TITLE
[1.7.10] Can't craft colored beds

### ISSUE THREAD

**Issue by danielrossyamitrano** [ZornTaov/BedcraftAndBeyond#14]
Whatever combination of wool I use, I get the same default Red and White bed. The color of the wood below does work, but I can't get any other color than the default on the bed sheets. I know there are newer versions of this mod for newer versions of minecraft, but I play on 1.7.10 because my modpack would be incomplete in another version.

**Comment by ZornTaov** [comment]
so... late reply, but I'm pretty sure at that point I had it so you rightclicked dye onto the head or the foot of the bed to change the color.
