### ISSUE TITLE
Branch Version Release Request - 1.8.9

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ZornTaov/BedcraftAndBeyond#3]
I love this mod for cosmetic reasons I was wondering you could start a branch for the 1.8.9 since it has superior chunk loading etc. Thank you in advance.

**Comment by ZornTaov** [comment]
not sure how chunk loading relates to what this mod does, but I as of right now I'm having problems with making my beds use woods from other mods that add planks to the oredict.  Once that is fixed and everything is stable I will attempt to update the mod to 1.8.9, but again not before things get fixed.  Also, not exactly sure how branching works, a bit of a newb when it comes to git features.

**Comment by P3rf3ctXZer0** [comment]
Its is technical for will happily update your mod with forge 1.8.9 as well and you know I understand wanting stability over all else.

**Comment by ZornTaov** [comment]
1.8.9 version released!

**Comment by P3rf3ctXZer0** [comment]
Thank you very much for your hard work :+1:
