### ISSUE TITLE
Crash report with Storage Drawers

### ISSUE THREAD

**Issue by davisjw** [ZornTaov/BedcraftAndBeyond#9]
BedcraftAndBeyond seems to crash when paired with Storage Drawers on the use a of a Compacting Drawer...
Error: java.lang.IndexOutOfBoundsException: Grid size too big to traverse.

Full error
http://pastebin.com/JBUqCaMa

Crashes when you put blocks or ingots in a compacting drawer..  does not seem to affect the regular drawer.

**Comment by davisjw** [comment]
SMP world....  havent tried SSP

**Comment by davisjw** [comment]
Havent tried adding Storage Drawers to the list yet..  was about to try.

**Comment by ZornTaov** [comment]
Please try using version 2.4.1 and tell us if the issue has been fixed

**Comment by davisjw** [comment]
appears to fix the issue...
